Update InputManager.cpp
hyprwm/Hyprland pull request #1879
Opened 2023-03-25 17:36 UTC by devil-may-c0de

#### Describe your PR, what does it fix/add?
fixes #1711 by adding a check for dragging when changing focus from moveMouseUnified in InputManager.cpp. This means that whenever a user drags a window, they cannot change focus with their mouse, and the focus stays on the window being dragged.

#### Is there anything you want to mention? (unchecked code, possible bugs, found problems, breaking compatibility, etc.)
Tested a few times before and after the patch. I was unable to change focus as described in #1711 with my patch, whereas without the patch I could reproduce the issue.

#### Is it ready for merging, or does it need work?
I don't know this script very well. It's possible that something has been slightly altered with the changes, but nothing was changed about follow_mouse behavior in my testing (apart from the bug being fixed)

2023-03-25 18:54 UTC, vaxerski requested changes
This is pretty bad as you're messing up the pointer coordinates sent to applications.

I'd rather suggest completely bailing out at like like 307 just after
```c
if (pFoundWindow) {
```
since we probably don't need to send pointer updates when dragging anyways.

2023-03-25 23:36 UTC, devil-may-c0de commented
ok! made the change.

2023-03-25 23:39 UTC, devil-may-c0de commented
i left the old code in i will fix that

2023-03-26 00:40 UTC, vaxerski commented
nuh-uh. You are still sending invalid coord events.

```cpp
if (pFoundWindow) {
    if (currently dragged)
        return;
```

there is no point in going further.

2023-03-26 01:05 UTC, devil-may-c0de commented
ah i see what you mean!

2023-03-26 01:40 UTC, devil-may-c0de commented
returning seems to break focusing. I don't think I'm the right person for this...

2023-03-26 01:40 UTC, closed without merging

2023-03-26 01:41 UTC, vaxerski commented
lmao I'll fix it

2023-05-01 04:19 UTC, yavko commented
> lmao I'll fix it

Is it fixed?

2023-05-01 14:16 UTC, vaxerski commented
ye d6b069458d990d372eaa9a35bb8726605b44a588