fix: prevent potential crash in handleBezier due to invalid input
hyprwm/Hyprland pull request #6246
Opened 2024-05-26 09:15 UTC by tachyglossues

#### Describe your PR, what does it fix/add?

before, when the conf file contained anything other than a float in the 4 bezier curve generation points for annimations, it crashed Hyprland, which now returns an error message.

#### Is there anything you want to mention? (unchecked code, possible bugs, found problems, breaking compatibility, etc.)

This is my first PR, so please check that I haven't done anything wrong. 

#### Is it ready for merging, or does it need work?

It's ready

2024-05-26 16:41 UTC, vaxerski commented on src/config/ConfigManager.cpp
> +        if (ARGS[1] == "" || ARGS[2] == "" || ARGS[3] == "" || ARGS[4] == "")
you can check .size

2024-05-26 20:00 UTC, tachyglossues commented on src/config/ConfigManager.cpp
> +        if (ARGS[1] == "" || ARGS[2] == "" || ARGS[3] == "" || ARGS[4] == "")
```suggestion
        if (ARGS.size() < 5)
```

2024-06-04 07:54 UTC, Micovec commented
Related #6249 I think that a util function should be created instead (as suggested by Vaxry in that issue).

2024-06-04 16:47 UTC, tachyglossues commented
> Related #6249 I think that a util function should be created instead (as suggested by Vaxry in that issue).

In this PR I've just fixed #6249 and I don't know if it's better to create a function. Because a simple try/catch is enough to solve this type of problem. And from the few tests I've done I haven't found the same problem elsewhere.

2024-06-04 17:08 UTC, Micovec commented
I don't want to be rude, but there are **many more** places with the same problem. Just look two lines up from your first change.

Also I'm not a reviewer but you don't want to do:

```cpp
...
} catch (...) {
    // An oopsie happened
}
```

It catches everything including things like [std::bad_alloc](https://en.cppreference.com/w/cpp/memory/new/bad_alloc).

2024-08-12 17:21 UTC, bakicelebi commented
@tachyglossues are you going to continue to work on this? This issue is annoying the hell out of me with vscode autosave. If you are not gonna continue working on this I will raise my own PR.

2024-08-13 19:47 UTC, tachyglossues commented
> @tachyglossues are you going to continue to work on this? This issue is annoying the hell out of me with vscode autosave. If you are not gonna continue working on this I will raise my own PR.

No, because the arguments are handled differently in the code, and I don't have the necessary C++ skills to refactor the code without making a disaster of it.

2024-09-30 09:01 UTC, vignesh1507 requested changes
You can add few type hints to your updated code snippet.

2024-12-08 18:41 UTC, closed without merging